/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["issueToken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/user/insert": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["addUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schedules/manage/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 일정 생성 API
     * @description 새로운 일정을 생성합니다.
     */
    post: operations["createSchedule"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schedules/manage/attend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 일정 참석/불참 API
     * @description 사용자가 일정에 참석 또는 불참 여부를 등록합니다.
     */
    post: operations["attendSchedule"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/files/upload/{category}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 이미지 업로드
     * @description 이미지 파일만 업로드를 허용하며 카테고리 정책에 따라 압축/거부가 적용됩니다.
     */
    post: operations["uploadImage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAllCrews"];
    put?: never;
    post: operations["createCrew"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crews/manage/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 크루에 가입할 수 있는 API
     * @description 크루에 가입 할 수 있습니다.
     */
    post: operations["joinCrew"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crews/manage/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 크루를 생성할 수 있는 API
     * @description 크루를 생성 할 수 있습니다.
     */
    post: operations["createCrew_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crew-members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 크루 멤버 생성
     * @description 크루에 멤버를 추가합니다.
     */
    post: operations["createCrewMember"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/communications/posts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 공지사항 또는 게시글을 조회하는 API
     * @description 크루 ID와 게시글 타입(notice 또는 post)을 전달하면 해당 게시글 리스트를 반환합니다.
     */
    get: operations["getPosts"];
    put?: never;
    /**
     * 공지사항 또는 게시글을 생성하는 API
     * @description 공지사항 또는 게시글을 생성합니다.
     */
    post: operations["createPost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/communications/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 댓글 생성 API
     * @description 부모 게시글 ID와 작성자 ID, 댓글 내용을 전달하여 댓글을 생성합니다.
     */
    post: operations["createComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/user/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getUserById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/user/name/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getUserByUserId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schedules/manage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 일정을 검색할 수 있는 API
     * @description 스케줄 제목, 설명, 크루명, 암장명 등을 기준으로 일정을 검색할 수 있습니다.
     */
    get: operations["searchSchedule"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schedules/manage/detail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 일정 상세 정보를 조회하는 API
     * @description 일정 ID를 기반으로 상세 정보를 조회할 수 있습니다.
     */
    get: operations["getScheduleInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/files/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 이미지 다운로드
     * @description 파일 id로 저장된 이미지를 다운로드합니다.
     */
    get: operations["downloadImage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crews/{crewId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCrew"];
    put?: never;
    post?: never;
    delete: operations["deleteCrew"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crews/manage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 크루를 검색할수 있는 API
     * @description 크루를 검색할 수 있습니다. keyword는 Like 검색이고 sort없을경우 최신값입니다. (size는 선택, 기본 10)
     */
    get: operations["searchCrew"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crews/manage/detail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 크루를 상세보기할수 있는 API
     * @description 크루를 상세보기 할 수 있습니다.
     */
    get: operations["searchDetailCrew"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crew-members/user/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 특정 유저가 속한 크루 멤버십 조회
     * @description 특정 유저가 속한 모든 크루 멤버십 정보를 조회합니다. // 멤버십 : 유저와 크루 간의 소속 관계 + 역할/상태 등의 부가 정보
     */
    get: operations["getMembershipsByUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crew-members/role/{role}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 역할 기반 크루 멤버 조회
     * @description 특정 역할을 가진 크루 멤버 목록을 조회합니다.
     */
    get: operations["getMembersByRole"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crew-members/crew/{crewId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 특정 크루 멤버 조회
     * @description 특정 크루에 속한 모든 멤버 목록을 조회합니다.
     */
    get: operations["getMembersByCrew"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/crew-members/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 유저-크루 멤버십 확인
     * @description 특정 유저가 특정 크루에 속해있는지 확인합니다.
     */
    get: operations["checkMembership"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/communications/newsfeed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 뉴스피드 조회 API
     * @description 크루 ID를 전달하면 해당 크루의 최신 공지 및 게시글 리스트를 반환합니다.
     */
    get: operations["getNewsfeed"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    IssueTokenResponseDto: {
      accessToken?: string;
      refreshToken?: string;
      tokenType?: string;
      /** Format: int64 */
      expiresIn?: number;
    };
    UserInsertDto: {
      userId?: string;
      userName?: string;
      email?: string;
      password?: string;
      profileImagePath?: string;
      mbti?: string;
      gender?: string;
      birth?: string;
      mainPicId?: string;
    };
    /** @description 일정 생성 요청 DTO */
    ScheduleCreateInDto: {
      /**
       * @description 제목
       * @example 주말 클라이밍 깜짝 이벤트
       */
      title: string;
      /**
       * @description 설명
       * @example 서울 암장에서 클라이밍 모임
       */
      description?: string;
      /**
       * Format: date-time
       * @description 시작 시간
       * @example 2025-09-25T10:00:00
       */
      startTime: string;
      /**
       * Format: date-time
       * @description 종료 시간
       * @example 2025-09-25T13:00:00
       */
      endTime: string;
      /**
       * @description 장소
       * @example 서울숲 볼더링 암장
       */
      location?: string;
      /**
       * @description 스케줄 타입
       * @example crew
       * @enum {string}
       */
      scheduleType: "crew" | "personal";
      /**
       * Format: int64
       * @description 크루 ID
       * @example 101
       */
      crewId?: number;
      /**
       * Format: int64
       * @description 암장 ID
       * @example 10
       */
      gymId?: number;
      /**
       * Format: int64
       * @description 작성자 ID
       * @example 202
       */
      userId: number;
    };
    /** @description 일정 생성 응답 DTO */
    ScheduleCreateOutDto: {
      /**
       * Format: int64
       * @description 생성된 일정 ID
       * @example 1
       */
      scheduleId?: number;
      /**
       * @description 생성 완료 메시지
       * @example 일정이 성공적으로 생성되었습니다.
       */
      message?: string;
    };
    /** @description 일정 참석/불참 요청 DTO */
    ScheduleAttendInDto: {
      /**
       * Format: int64
       * @description 일정 ID
       * @example 1
       */
      scheduleId: number;
      /**
       * Format: int64
       * @description 사용자 ID
       * @example 202
       */
      userId: number;
      /**
       * @description 참석 여부
       * @example true
       */
      attend: boolean;
    };
    /** @description 일정 참석/불참 응답 DTO */
    ScheduleAttendOutDto: {
      /**
       * @description 처리 완료 메시지
       * @example 참석이 등록되었습니다.
       */
      message?: string;
    };
    infoDto: {
      /** Format: uuid */
      id?: string;
      originalName?: string;
      /** Format: int64 */
      fileSize?: number;
      contentType?: string;
      fileExt?: string;
    };
    CrewCreateInDto: {
      crewName?: string;
      description?: string;
      recruitmentStatus?: string;
      isPublic?: boolean;
      region?: string;
      preferredAge?: string;
      /** Format: int64 */
      mainPicId?: number;
      /** Format: int64 */
      ownerId?: number;
    };
    JoinCrewInDto: {
      /**
       * @description 가입인사
       * @example 안녕하세요 주로 구로에서 클라이밍하고 있는 양지웅입니다..
       */
      content?: string;
      /**
       * Format: int64
       * @description 크루 Id
       */
      crewId?: number;
    };
    CreateInDto: {
      crewName?: string;
      description?: string;
      recruitmentStatus?: string;
      isPublic?: boolean;
      region?: string;
      preferredAge?: string;
      mainPicId?: string;
      /** Format: int64 */
      ownerId?: number;
    };
    /** @description 크루 멤버 생성 요청 DTO */
    CrewMemberCreateInDto: {
      /**
       * Format: int64
       * @description 크루 ID
       * @example 45
       */
      crewId: number;
      /**
       * Format: int64
       * @description 유저 ID
       * @example 202
       */
      userId: number;
      /**
       * @description 멤버 역할
       * @example MEMBER
       */
      role: string;
    };
    /** @description 크루 멤버 DTO */
    CrewMemberDto: {
      /**
       * Format: int64
       * @description 크루 멤버 ID
       * @example 123
       */
      crewMemberId?: number;
      /**
       * Format: int64
       * @description 크루 ID
       * @example 45
       */
      crewId?: number;
      /**
       * Format: int64
       * @description 유저 ID
       * @example 202
       */
      userId?: number;
      /**
       * @description 멤버 역할
       * @example ADMIN
       */
      role?: string;
      /**
       * @description 유저 로그인 아이디
       * @example yoyo326
       */
      userLoginId?: string;
      /**
       * @description 유저 이름
       * @example Yoyo
       */
      userName?: string;
    };
    /** @description 공지/게시글 생성 요청 DTO */
    PostCreateInDto: {
      /**
       * Format: int64
       * @description 크루 ID
       * @example 101
       */
      crewId: number;
      /**
       * Format: int64
       * @description 작성자 ID
       * @example 202
       */
      userId: number;
      /**
       * @description 제목
       * @example 정모 일정 안내
       */
      title: string;
      /**
       * @description 내용
       * @example 다음 주 토요일 2시에 만나요.
       */
      content: string;
      /**
       * @description 게시글 타입
       * @example notice
       * @enum {string}
       */
      type: "notice" | "post";
      pinned?: boolean;
    };
    /** @description 공지/게시글 생성 응답 DTO */
    PostCreateOutDto: {
      /**
       * Format: int64
       * @description 게시글 ID
       * @example 1
       */
      communicationId?: number;
      /**
       * @description 메시지
       * @example 게시글이 성공적으로 작성되었습니다.
       */
      message?: string;
    };
    /** @description 댓글 작성 요청 DTO */
    CommentCreateInDto: {
      /**
       * Format: int64
       * @description 부모 게시글 ID
       * @example 1
       */
      parentId: number;
      /**
       * Format: int64
       * @description 작성자 ID
       * @example 202
       */
      userId: number;
      /**
       * @description 댓글 내용
       * @example 재밌었어요!
       */
      content: string;
    };
    /** @description 댓글 작성 응답 DTO */
    CommentCreateOutDto: {
      /**
       * Format: int64
       * @description 댓글 ID
       * @example 10
       */
      commentId?: number;
      /**
       * @description 메시지
       * @example 댓글이 등록되었습니다.
       */
      message?: string;
    };
    UserEntity: {
      /** Format: int64 */
      id?: number;
      userId?: string;
      userName?: string;
      email?: string;
      password?: string;
      profileImagePath?: string;
      mbti?: string;
      gender?: string;
      birth?: string;
      mainPicId?: string;
    };
    /** @description 일정 검색 결과 DTO */
    ScheduleSearchOutDto: {
      /**
       * Format: int64
       * @description 일정ID
       * @example 1
       */
      id?: number;
      /**
       * @description 제목
       * @example 주말 클라이밍 번개
       */
      title?: string;
      /**
       * @description 설명
       * @example 서울 암장에서 클라이밍 모임
       */
      description?: string;
      /**
       * Format: date-time
       * @description 시작 시간
       * @example 2025-09-25T10:00:00
       */
      startTime?: string;
      /**
       * Format: date-time
       * @description 종료 시간
       * @example 2025-09-25T13:00:00
       */
      endTime?: string;
      /**
       * @description 장소
       * @example 서울숲 볼더링 암장
       */
      location?: string;
      /**
       * @description 스케줄 타입
       * @example crew
       * @enum {string}
       */
      scheduleType?: "crew" | "personal";
      /**
       * @description 크루 이름
       * @example YoyoCrew
       */
      crewName?: string;
      /**
       * @description 작성자 이름
       * @example Yoyo
       */
      createdBy?: string;
    };
    /** @description 일정 상세 정보 DTO */
    ScheduleDetailOutDto: {
      /**
       * Format: int64
       * @description 일정 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 제목
       * @example 평일 저녁 클라이밍
       */
      title?: string;
      /**
       * @description 설명
       * @example 볼더링 모임
       */
      description?: string;
      /**
       * Format: date-time
       * @description 시작 시간
       * @example 2025-09-22T18:00:00
       */
      startTime?: string;
      /**
       * Format: date-time
       * @description 종료 시간
       * @example 2025-09-22T20:00:00
       */
      endTime?: string;
      /**
       * @description 장소
       * @example 더클라임 홍대점
       */
      location?: string;
      /**
       * @description 스케줄 타입
       * @example crew
       * @enum {string}
       */
      scheduleType?: "crew" | "personal";
      /**
       * @description 크루 이름
       * @example YoyoCrew
       */
      crewName?: string;
      /**
       * @description 암장 이름
       * @example 더클라임 홍대점
       */
      gymName?: string;
      /**
       * @description 작성자 이름
       * @example Yoyo
       */
      createdBy?: string;
    };
    CrewDto: {
      /** Format: int64 */
      crewId?: number;
      crewName?: string;
      description?: string;
      recruitmentStatus?: string;
      isPublic?: boolean;
      /** Format: int32 */
      memberCount?: number;
      region?: string;
      preferredAge?: string;
      /** Format: float */
      activityScore?: number;
      /** Format: int64 */
      mainPicId?: number;
      /** Format: int64 */
      ownerId?: number;
      ownerUserId?: string;
    };
    /** @description 크루 검색 결과 아이템 DTO */
    CrewSearchOutDto: {
      /**
       * Format: int64
       * @description 크루 ID
       * @example 101
       */
      crewId?: number;
      /**
       * @description 크루명
       * @example 서울 클라이밍 크루
       */
      crewName?: string;
      /**
       * @description 크루 소개/설명
       * @example 서울 지역 암벽/볼더링을 즐기는 모임입니다.
       */
      description?: string;
      /**
       * Format: int32
       * @description 현재 멤버 수
       * @example 24
       */
      memberCount?: number;
      /**
       * @description 활동 지역
       * @example 서울
       */
      region?: string;
      /**
       * @description 선호 연령대
       * @example 20대
       * @enum {string}
       */
      preferredAge?: "10대" | "20대" | "30대" | "40대" | "50대이상";
      /**
       * Format: float
       * @description 활동 점수 (0.0~5.0)
       * @example 4.3
       */
      activityScore?: number;
      /**
       * @description 메인 사진 id
       * @example 8f2a1bkklf
       */
      mainPicId?: string;
    };
    PageCrewSearchOutDto: {
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      first?: boolean;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["CrewSearchOutDto"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      last?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components["schemas"]["SortObject"];
      unpaged?: boolean;
      paged?: boolean;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
    };
    SortObject: {
      empty?: boolean;
      unsorted?: boolean;
      sorted?: boolean;
    };
    CrewDetailOutDto: {
      /**
       * Format: int64
       * @description 크루 ID
       * @example 1
       */
      crewId?: number;
      /**
       * @description 크루명
       * @example 서울 클라이밍
       */
      crewName?: string;
      /**
       * @description 설명
       * @example 서울 클라이밍크루
       */
      description?: string;
      /**
       * @description 모집 상태
       * @example RECRUITING
       * @enum {string}
       */
      recruitmentStatus?: "RECRUITING" | "CLOSED" | "PAUSED";
      /**
       * @description 공개 여부
       * @example true
       */
      isPublic?: boolean;
      /**
       * Format: int32
       * @description 멤버 수
       * @example 49
       */
      memberCount?: number;
      /**
       * @description 지역
       * @example 영등포구
       */
      region?: string;
      /**
       * @description 선호 연령대
       * @example 30대
       * @enum {string}
       */
      preferredAge?: "10대" | "20대" | "30대" | "40대" | "50대이상";
      /**
       * Format: float
       * @description 활동 점수(0.0~5.0)
       * @example 4.7
       */
      activityScore?: number;
      /**
       * Format: int64
       * @description 메인 사진 ID
       * @example 1001
       */
      mainPicId?: number;
      /**
       * @description 크루장 이름
       * @example 홍길동
       */
      ownerName?: string;
    };
    /** @description 크루 멤버 조회 응답 DTO */
    CrewMemberSearchOutDto: {
      /**
       * Format: int64
       * @description 크루 멤버 ID
       * @example 202
       */
      crewMemberId?: number;
      /**
       * @description 멤버 역할
       * @example ADMIN
       */
      role?: string;
      /** @description 유저 정보 */
      user?: components["schemas"]["UserInfo"];
    };
    /** @description 유저 정보 DTO */
    UserInfo: {
      /**
       * Format: int64
       * @description 유저 내부 ID
       * @example 789
       */
      id?: number;
      /**
       * @description 유저 로그인 아이디
       * @example yoyo326
       */
      userId?: string;
      /**
       * @description 유저 이름
       * @example Yoyo
       */
      userName?: string;
    };
    /** @description 공지/게시글 조회 요청 DTO */
    PostSearchInDto: {
      /**
       * Format: int64
       * @description 크루 ID
       * @example 101
       */
      crewId: number;
      /**
       * @description 게시글 타입
       * @example notice
       * @enum {string}
       */
      type: "notice" | "post";
    };
    /** @description 공지/게시글 조회 응답 DTO */
    PostSearchOutDto: {
      /**
       * Format: int64
       * @description 게시글 ID
       * @example 1
       */
      communicationId?: number;
      /**
       * @description 제목
       * @example 다음 주 정모 일정 안내
       */
      title?: string;
      /**
       * @description 내용
       * @example 일정은 다음 주 토요일입니다.
       */
      content?: string;
      /**
       * @description 작성자 이름
       * @example Yoyo
       */
      createdBy?: string;
      /**
       * Format: date-time
       * @description 작성 시간
       * @example 2025-09-21T10:30:00
       */
      createdAt?: string;
      /**
       * @description 게시글 타입
       * @example notice
       * @enum {string}
       */
      type?: "notice" | "post";
      pinned?: boolean;
    };
    /** @description 뉴스피드 조회 응답 DTO */
    NewsfeedOutDto: {
      /**
       * Format: int64
       * @description 게시글 ID
       * @example 1
       */
      communicationId?: number;
      /**
       * @description 제목
       * @example 이번 주 모임 후기
       */
      title?: string;
      /**
       * @description 내용
       * @example 재미있었어요!
       */
      content?: string;
      /**
       * @description 작성자 이름
       * @example Yoyo
       */
      createdBy?: string;
      /**
       * Format: date-time
       * @description 작성일시
       * @example 2025-09-20T16:00:00
       */
      createdAt?: string;
      /**
       * @description 게시글 타입
       * @example post
       * @enum {string}
       */
      type?: "notice" | "post";
      /**
       * Format: int32
       * @description 댓글 수
       * @example 5
       */
      commentCount?: number;
      /**
       * Format: int32
       * @description 좋아요 수
       * @example 12
       */
      likeCount?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  issueToken: {
    parameters: {
      query: {
        grant_type: string;
        scope?: string;
        username?: string;
        password?: string;
        refresh_token?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["IssueTokenResponseDto"];
        };
      };
    };
  };
  addUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserInsertDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": number;
        };
      };
    };
  };
  createSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduleCreateInDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ScheduleCreateOutDto"];
        };
      };
    };
  };
  attendSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduleAttendInDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ScheduleAttendOutDto"];
        };
      };
    };
  };
  uploadImage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 이미지 카테고리(ICON, PROFILE, FEED, BOARD)
         * @example PROFILE
         */
        category: "ICON" | "PROFILE" | "FEED" | "BOARD";
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @description 업로드할 이미지 파일
           */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["infoDto"];
        };
      };
    };
  };
  getAllCrews: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CrewDto"][];
        };
      };
    };
  };
  createCrew: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CrewCreateInDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": number;
        };
      };
    };
  };
  joinCrew: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinCrewInDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createCrew_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createCrewMember: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CrewMemberCreateInDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CrewMemberDto"];
        };
      };
    };
  };
  getPosts: {
    parameters: {
      query: {
        postSearchInDto: components["schemas"]["PostSearchInDto"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PostSearchOutDto"][];
        };
      };
    };
  };
  createPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PostCreateInDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PostCreateOutDto"];
        };
      };
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentCreateInDto"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CommentCreateOutDto"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": string;
        };
      };
    };
  };
  getUserById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserEntity"];
        };
      };
    };
  };
  getUserByUserId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserEntity"];
        };
      };
    };
  };
  searchSchedule: {
    parameters: {
      query?: {
        /**
         * @description 검색 키워드(제목, 설명 등)
         * @example 서울 클라이밍 일정
         */
        keyword?: string;
        /**
         * @description 크루 ID로 필터링
         * @example 101
         */
        crewId?: number;
        /**
         * @description 암장 ID로 필터링
         * @example 10
         */
        gymId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ScheduleSearchOutDto"][];
        };
      };
    };
  };
  getScheduleInfo: {
    parameters: {
      query: {
        /**
         * @description 일정 ID
         * @example 1
         */
        id: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ScheduleDetailOutDto"];
        };
      };
    };
  };
  downloadImage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 파일 UUID(v7) id
         * @example 019988f4-fe3a-7efd-9646-90223c3fbe8c
         */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
    };
  };
  getCrew: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        crewId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CrewDto"];
        };
      };
    };
  };
  deleteCrew: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        crewId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  searchCrew: {
    parameters: {
      query?: {
        /**
         * @description 검색 키워드 (크루명, 설명, 지역 등)
         * @example 클아이밍
         */
        keyword?: string;
        /**
         * @description 지역 필터
         * @example 서울
         */
        region?: string;
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageCrewSearchOutDto"];
        };
      };
    };
  };
  searchDetailCrew: {
    parameters: {
      query: {
        /**
         * @description 크류 ID
         * @example 1
         */
        crewId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CrewDetailOutDto"];
        };
      };
    };
  };
  getMembershipsByUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CrewMemberDto"][];
        };
      };
    };
  };
  getMembersByRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        role: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CrewMemberSearchOutDto"][];
        };
      };
    };
  };
  getMembersByCrew: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        crewId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CrewMemberSearchOutDto"][];
        };
      };
    };
  };
  checkMembership: {
    parameters: {
      query: {
        crewId: number;
        userId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CrewMemberDto"];
        };
      };
    };
  };
  getNewsfeed: {
    parameters: {
      query: {
        crewId: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["NewsfeedOutDto"][];
        };
      };
    };
  };
}
